// {
//                 title: "Zhaleika", 
//                 id: "zhaleika", 
//                 caroussel_images : [
//                 "zhaleika_Still 01.jpg",
//                 "zhaleika_Still 02.jpg",
//                 "zhaleika_Still 03.jpg",
//                 "zhaleika_Still 04.jpg",
//                 "zhaleika_Still 05.jpg",
//                 "zhaleika_Still 06.jpg",
//                 "zhaleika_Still 07.jpg"
//                 ],
//                 synopsis: "Lora, ein 17 jähriges Mädchen wird mit dem Tod ihres Vaters konfrontiert. In dem kleinen bulgarischen Dorf, wo die Zeit stehengeblieben zu sein scheint, erwarten ihre Familie und die Dorfbewohner, dass sie sich ihrer Trauer hingibt. Ab jetzt muss sie Schwarz tragen, darf keine Musik hören und muss diverse Trauerrituale beachten. Dabei will Lora ihre Jugend weiterhin ausleben. Ihr Wunsch aber wird durch den urteilenden Blick der anderen unterbunden, die sie dazu zwingen die Opferrolle eines Waisenkindes zu bedienen.", 
//                 trailer: "Zhaleika Trailer.mp4",
//                 stats_1: [
//                 "Kurzfilm, Deutschland 2014, 13 min", 
//                 "ARRI Amira, Dolby Digital 5.1"
//                 ],
//                 stats_2: {
//                 Vorführformate: "DCP, Blu-Ray, Quicktime", 
//                 Originalsprache: "Deutsch", 
//                 Untertitel: "Englisch, Französisch" 
//                 },
//                 poster : "Zhaleika Poster.jpg", 
//                 cast: [
//                 "ANNA MANOLOVA", 
//                 "SNEZHINA PETROVA", 
//                 "MIHAIL STOYANOV", 
//                 "MARIA KLECHEVA", 
//                 "STOYKO IVANOV", 
//                 "BOYANA GEORGIEVA", 
//                 "ASYA POPOVA", 
//                 "MÁRTON NAGY"
//                 ], 
//                 team: {
//                 Buch_und_Regie: "ELIZA PETKOVA",
//                 Bildgestaltung : "CONSTANZE SCHMITT", 
//                 Originalton : "HANNES MARGET",
//                 Kostümbild: "WARIS KLAMPFER",
//                 Licht: "DAVID SCHMITT",
//                 Szenenbild: "HRISTINA DYAKOVA, JANET IVANOVA",
//                 Produktion: "SVETOSLAV DRAGANOV, TIM OLIVER SCHULTZ, CÉCILE TOLLU-POLONOWSKI",
//                 Regieassistenz_und_Set: "PETAR PETROV",
//                 Produktionassistenz: "TSVETA ERMENKOVA",
//                 Kameraassistenz: "MALTE SIEPEN, CRISTINA AMATE GARCIA",
//                 Set_Runner: "GALIN POPOV, VESSELIN DENEV",
//                 Catering: "TEST DIMITRINKA SEMKOVA",
//                 Schnitt: "HANNES MARGET, ELIZA PETKOVA",
//                 Tongestaltung: "HANNES MARGET, JOSCHA EICKEL",
//                 Grading: "CHRISTINE HIAM, CONSTANZE SCHMITT",
//                 Tonmischung: "SILVIO NAUMANN",
//                 Geräuschemacher: "PETER ROJGK",
//                 Herstellungsleitung_DFFB: "ANDREAS LOUIS",
//                 Produzent: "DEUTSCHE FILM- UND FERNSEHAKADEMIE BERLIN"
//                 },
//                 awards: [ 
//                 "66. Berlinale - Internationale Filmfestspiele Berlin - Generation",
//                 "20th International Sofia Film Festival - International Competition",
//                 "56th Zlin Film Festival, Czech Republic",
//                 "The Golden Linden International Film Festival of New European Cinema, Bulgaria",
//                 "31th Festival Internacional de Cine de Valencia CINEMA JOVE, Spain",
//                 "2Cinema City International Film Festival Novi Sad, Serbia",
//                 "Burgas International Film Festival, Bulgaria",
//                 "10. Internationales Fünf Seen Festival, Germany",
//                 "Cinematik International Film Festival, Slovakia",
//                 "9th Cine East, Luxembourg",
//                 "Film Fest Gent, Belgium",
//                 "39th Mill Valley Film Festival, California, USA",
//                 "Balkanmania, Istanbul Modern, Turkey",
//                 "33th Chicago International Children’s Film Festival, USA",
//                 "35th Oulu International Children's and Youth Film Festival, Finland",
//                 "23th Minsk International Film Festival, Belarus",
//                 "Cinedays Skopje, Makedonia",
//                 "Zagreb Film Festival, Croatia",
//                 "Tbilisi International Film Festival, Georgia",
//                 "Küstendorf Film and Music Festival, Serbia",
//                 "15th Pune International Film Festival PIFF, India",
//                 "Lets Cee Film Festival, Vienna, Austria",
//                 "Kinotrip Filmfestival, Ljubljana, Slovenia",
//                 "18th Stockholm International Film Festival Junior, Sweden",
//                 "Sehsüchte 46th Student Film Festival, Germany" 
//                 ] 
// },